### PR TITLE
feature/eckit-codec

### PR DESCRIPTION
**Pull request by pmaciel**
Hi,

this is a port of the atlas_io library into eckit, here called eckit "codec". It generaly lives under the namespace "eckit::codec" and is pretty much what altas_io is, plus a much stronger integration into eckit (some overlapping functionality were removed) and some refactorings. 

It does not have some changes (yet) that would be really nice, and have been previously discussed, such as
- user (runtime) configurable record begin/end (currently "ATLAS-IO"/"ATLAS-IO-END" so that existing ORCA grids in this format remain compatible); This is currently controlled at cmake time, although there is some string arithmetic that might break if it is different (not sure).
- user (runtime) configurable format -- which fields in which order is currently hardcoded (as in atlas_io)
- remove writing into the std:: namespace

I've removed some logic for older compilers and pre-C++-17. The tests run, I haven't added any new. The code is behind the cmake option ENABLE_EXPERIMENTAL.

Feel free to discuss and further contribute -- I'm certainly not expecting a merge to happen immediately, although that would make my life easier :-)

### CODE REVIEW

**Comment by pmaciel** [comment]
Apologies for (previously) touching the develop branch with these changes. I had a strange configuration of locally a correctly-named branch ("feature/eckit-geo") pointing to the wrong remote branch ("develop"!) -- obviously I've reverted this and it's all back to normal.

**Comment by wdeconinck** [comment]
Hi @pmaciel I have contributed to the branch with a few orthogonal commits.
The first one was a bug fix on the configuration of static_assert.
The other ones were related to trying to use eckit::codec in atlas and downstream plugins with minimal changes.

I also started working on the atlas_io library to be an adaptor library, delegating all calls to use eckit_codec.
We can then gradually port in the future.

**Review by iainrussell — APPROVED** [review]

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf/eckit?pullRequest=86) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/eckit?pullRequest=86) before we can accept your contribution.<br/><hr/>**Pedro Maciel** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/eckit?pullRequest=86) it.</sub>

**Review by wdeconinck — APPROVED** [review]
I like your additions @pmaciel this is all good to merge as far as I'm concerned.

**Review by dsarmany — APPROVED** [review]
This looks fine. We have some developments (for ERA6) that currently use `atlas_io`, but swapping it out to this is a minimal effort. So it is a good state to start in eckit. Thank you, Pedro!

A lot of things to discuss down the line, of course, not least how to choose from the various serialisation options available in eckit right now, and how `eckit/codec` (formerly `atlas_io`) compares with `eckit/io`, etc.

**Pull request merged**
