### PR TITLE
Add isNull to eckit::Configuration

### PR DESCRIPTION
**Pull request by geier1993**
I would like to check properly if a value ina yaml configuration is NULL.
Otherwise I can just guess that a value is null by exclusion (when all the other introspective calls are false).

### CODE REVIEW

**Review by pmaciel — APPROVED** [review]
This makes sense; Note, the current eckit::Value instrospection methods list:
isBoolean
isBooleanList
isFloatingPoint
isFloatingPointList
isIntegral
isIntegralList
isList
isString
isStringList
isSubConfiguration
isSubConfigurationList
isNull (new)

is not very similar to the eckit::Content:
isBool
isDate
isDateTime
isDouble
isList
isMap
isNumber
isOrderedMap
isString
isTime
isNil

neither to the standard <type_traits>, which I believe that's where we should head. But until this is changed, this is a improvement :smiley::+1:

**Review by wdeconinck — APPROVED** [review]

**Comment by wdeconinck** [comment]
Just one more thing… a unit test 🤓

**Comment by geier1993** [comment]
> Just one more thing… a unit test 🤓

added a test

**Comment by dsarmany** [comment]
Only the multio-python CI fails which has nothing to do with this change and is being looked into.

**Pull request merged**
