### PR TITLE
Add cross product for Point3

### PR DESCRIPTION
**Pull request by pmarguinaud**
Solves issue #23

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](http://claassistant.ecmwf.int:80/ecmwf/eckit?pullRequest=25) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf/eckit?pullRequest=25) before we can accept your contribution.<br/><hr/>**MARGUINAUD Philippe** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf/eckit?pullRequest=25) it.</sub>

**Comment by tlmquintino** [comment]
Hi. The code is ok, but you do need to sign the CLA agreement before I can accept the merge.
Please also add the email in the commit to your GitHub account.

**Comment by pmarguinaud** [comment]
Hi Tiago,

I have signed the CLA and added my email in my user profile. The pull request page says : 
"license/cla Pending — Contributor License Agreement is not signed yet. "

Do I need to do something else ?

**Comment by wdeconinck** [comment]
> Hi Tiago,
> 
> I have signed the CLA and added my email in my user profile. The pull request page says :
> "license/cla Pending — Contributor License Agreement is not signed yet. "
> 
> Do I need to do something else ?

Are you sure that you added the email "philippe.marguinaud@meteo.fr" , and as well signed with that email?

**Comment by pmarguinaud** [comment]
Hello Willem,

I have signed the CLA with this address : pmarguinaud@hotmail.com; when I try to sign again, the CLA page says : "You have signed the Contributor License Agreement for ecmwf/eckit". There I see my name and my private email address (pmarguinaud@hotmail.com). 
I have also added this email address to my github profile; when I go to my profile; you can see that here : https://github.com/pmarguinaud. 
What else should I do ?

Philippe

**Comment by tlmquintino** [comment]
This looks good to merge now

**Pull request merged**
