### PR TITLE
Add extended SFINAE capabilities for eckit::Translator

### PR DESCRIPTION
**Pull request by geier1993**
I added a predicate `IsTranslatable` that test for an existing and valid implementation.

Todo so I had to change the default operator to an auto type - otherwise the return type can be deduced without evaluating the overload set properly.

I'm using this in a new multio feature branch with an variant based Metadata class (instead of LocalConfiguration).
The compilation already included mir (develop), metkit and fdb.

Not all of these packages already use C++17. Hence I added some compiler flags.

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf/eckit?pullRequest=78) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/eckit?pullRequest=78) before we can accept your contribution.<br/><hr/>**Philipp Geier** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/eckit?pullRequest=78) it.</sub>

**Review by simondsmart — APPROVED** [review]
After review work today, all approved.

**Review by simondsmart — APPROVED** [review]
Please fix the mismatched comment that I've already noted, and then merge.

**Comment by geier1993** [comment]
> ## [Codecov](https://app.codecov.io/gh/ecmwf/eckit/pull/78?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ecmwf) Report
> 
> Attention: `2 lines` in your changes are missing coverage. Please review.
> 
> > Comparison is base [(`ffdee81`)](https://app.codecov.io/gh/ecmwf/eckit/commit/ffdee817e1509fa773a522406b3637f79fbbeacf?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ecmwf) 62.85% compared to head [(`29a19c9`)](https://app.codecov.io/gh/ecmwf/eckit/pull/78?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ecmwf) 62.19%.
> > Report is 60 commits behind head on develop.
> 
> [Files](https://app.codecov.io/gh/ecmwf/eckit/pull/78?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ecmwf) 	Patch % 	Lines
> [src/eckit/utils/Translator.h](https://app.codecov.io/gh/ecmwf/eckit/pull/78?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ecmwf#diff-c3JjL2Vja2l0L3V0aWxzL1RyYW5zbGF0b3IuaA==) 	0.00% 	[2 Missing ⚠️ ](https://app.codecov.io/gh/ecmwf/eckit/pull/78?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ecmwf)
> Additional details and impacted files
> 
> [☔ View full report in Codecov by Sentry](https://app.codecov.io/gh/ecmwf/eckit/pull/78?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ecmwf). 📢 Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ecmwf).

I don't think the tool is correct. The templated lines (https://app.codecov.io/gh/ecmwf/eckit/pull/78?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ecmwf#fa32d6530b7a2107fff999390cf9a157-R39) are used by `eckit::Resource`....

I added a further test that uses it as well

**Pull request merged**
