### PR TITLE
Check for empty Configuration

### PR DESCRIPTION
**Pull request by ytremolet**
This could also be achieved by a method instead of an operator bool() if preferred. Unless there is already another way to achieve the same result but I couldn't find one.

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](http://claassistant.ecmwf.int:80/ecmwf/eckit?pullRequest=28) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf/eckit?pullRequest=28) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf/eckit?pullRequest=28) it.</sub>

**Comment by tlmquintino** [comment]
@ytremolet thanks for the contribution and the adjoining unit test.
I think I should be an empty() method (as in the class std::string), as it refers more to the "content" of the configuration. If you do the update I will merge it in.

**Comment by tlmquintino** [comment]
@ytremolet can you please check that you have signed the CLA agreement and that it the email you committed with in git is associated to the github account that signed the agreement.

**Comment by ytremolet** [comment]
Changed the name to empty() method.
The email is the same, and the fussy duck looks happy from here.

**Comment by tlmquintino** [comment]
Internal tests at ECMWF test system passed.
Rebased this on top of develop and merged it in.

**Pull request closed without merging**
