### PR TITLE
Contributions from JCSDA

### PR DESCRIPTION
**Pull request by benjaminmenetrier**
Hello, this PR contains recent contributions added at JCSDA (@wsmigaj, @mmiesch and @markjolah) to the `develop` branch of the ECMWF repo:
 - Made Test take and store std::function objects instead of function pointers:
    + src/eckit/testing/Test.h
 - Extended KDNode with a public method returning the node's splitting axis:
    + src/eckit/container/kdtree/KNode.h:
 - Bugfix/intel19 test mpi:
    +  tests/mpi/CMakeLists.txt
 - Moved the EXPECT_EQUAL macro from oops to eckit:
    +  src/eckit/testing/Test.h
    +  tests/testing/test_testing.cc

I don't know why GitHub says "88 files changed" and does not show the `develop` branch of ECMWF repo on the left side of the comparison, as it should.

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](http://claassistant.ecmwf.int:80/ecmwf/eckit?pullRequest=26) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf/eckit?pullRequest=26) before we can accept your contribution.<br/>**2** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: benjaminmenetrier<br/>:white_check_mark: wsmigaj<br/>:x: markjolah<br/>:x: rhoneyager<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf/eckit?pullRequest=26) it.</sub>

**Comment by benjaminmenetrier** [comment]
OK, I see. I didn't used the latest `develop`version. I'm closing this PR and reopening it soon.

**Comment by benjaminmenetrier** [comment]
@mmiesch had the solution: I merged `ecmwf:develop` into `jcsda:develop-jcsda` with the "ours" strategy:
```
git checkout develop-jcsda
git merge -s ours ecmwf/develop
```
Now, only the 4 changed files appear.

**Comment by wdeconinck** [comment]
Thank you for the contributions
For future reference the issues/pull-requests have to be separated to be able to discuss on each.

- I noticed however that the change in `Test.h`(the first bullet point) is already partly covered in PR https://github.com/ecmwf/eckit/pull/18  (@tlmquintino could you comment?)

- The second bullet point about KDNode is already covered in PR https://github.com/ecmwf/eckit/pull/19

- I know that the `EXPECT_EQUAL` macro is controversial, and will need a separate Issue (not a Pull-request) @tlmquintino will offer a better proposal.

- About the Intel 19.0.5 MPI problem. We already had seen and fixed the actual code problem (which we also started noticing with Intel 19.0.4) in commit f5c1f1879d6. You should not need those changes in CMake any longer.

**Comment by benjaminmenetrier** [comment]
I think all the JCSDA's contributions have been merged into ECMWF `develop`, so I'm closing this PR. Thanks a lot @wdeconinck for your help and reactivity.

**Pull request closed without merging**
